// Final expansion batch - targeting 3,000+ legacy questions total
import { LegacyQuestionTemplate } from './legacy-questions'

export const finalLegacyQuestions: LegacyQuestionTemplate[] = [
  // PARENTAL WISDOM - Teaching Life Skills
  {
    category: 'parental_wisdom',
    subcategory: 'life_skills_teaching',
    familyRoles: ['parent', 'grandparent'],
    emotionalDepth: 7,
    tags: ['skills', 'independence', 'capability', 'self_reliance'],
    questions: [
      "What essential life skills should every person master before living independently?",
      "How do you teach children to manage their time and prioritize responsibilities?",
      "What's your approach to teaching kids about personal hygiene and self-care?",
      "How do you help children develop critical thinking and problem-solving abilities?",
      "What's the most important thing about teaching kids to cook and feed themselves?",
      "How do you teach children to manage their emotions and emotional intelligence?",
      "What's your approach to teaching kids about personal safety and street smarts?",
      "How do you help children develop good study habits and learning strategies?",
      "What's the secret to teaching kids to be organized and keep their spaces clean?",
      "How do you teach children to advocate for themselves and speak up when needed?",
      "What's your approach to teaching kids about basic car maintenance and repairs?",
      "How do you help children develop social skills and make friends?",
      "What's the most important thing about teaching kids to handle emergencies?",
      "How do you teach children to budget money and make smart financial choices?",
      "What's your approach to teaching kids about basic home maintenance and repairs?",
      "How do you help children develop their own moral compass and decision-making?",
      "What's the secret to teaching kids to be independent without being selfish?",
      "How do you teach children to handle conflict and difficult conversations?",
      "What's your approach to teaching kids about personal boundaries and consent?",
      "How do you help children develop resilience and bounce back from setbacks?",
      "What's the most important thing about teaching kids to take care of their health?",
      "How do you teach children to be curious learners throughout their lives?",
      "What's your approach to teaching kids about leadership and taking initiative?",
      "How do you help children develop their unique talents and interests?",
      "What's the secret to teaching kids to be helpful and contributing family members?",
      "How do you teach children to handle technology responsibly and safely?",
      "What's your approach to teaching kids about cultural awareness and respect?",
      "How do you help children develop confidence in trying new things?",
      "What's the most important thing about teaching kids to recover from mistakes?",
      "How do you teach children to balance independence with asking for help when needed?"
    ]
  },

  // LOVE & RELATIONSHIPS - Building Trust
  {
    category: 'love_relationships',
    subcategory: 'building_trust',
    familyRoles: ['parent', 'grandparent', 'spouse'],
    emotionalDepth: 9,
    tags: ['trust', 'reliability', 'honesty', 'faith', 'security'],
    questions: [
      "What does it really mean to be trustworthy in all your relationships?",
      "How do you rebuild trust after you've broken it through your actions?",
      "What's the difference between trusting someone and being naive about their flaws?",
      "How do you know when someone has earned your deep trust and confidence?",
      "What's your approach to being vulnerable with people you trust?",
      "How do you handle it when someone you trust deeply disappoints you?",
      "What's the most important thing about keeping confidences and secrets?",
      "How do you show others that they can depend on you completely?",
      "What's your philosophy about trusting people's words versus their actions?",
      "How do you handle situations where trust needs to be verified?",
      "What's the secret to maintaining trust in long-term relationships?",
      "How do you trust your instincts about people while giving them fair chances?",
      "What's your approach to trusting family members who have hurt you before?",
      "How do you balance being trusting with protecting yourself from harm?",
      "What's the most important thing about earning trust through consistency?",
      "How do you handle broken promises in relationships you care about?",
      "What's your philosophy about second chances and rebuilding broken trust?",
      "How do you show trust in others without setting yourself up for disappointment?",
      "What's your approach to trusting new people while being appropriately cautious?",
      "How do you maintain trust when going through difficult times together?",
      "What's the secret to trusting others with your deepest fears and insecurities?",
      "How do you handle situations where trust has been shattered completely?",
      "What's your approach to building trust gradually versus giving it freely?",
      "How do you know the difference between healthy skepticism and damaging distrust?",
      "What's the most important thing about being someone others can trust implicitly?",
      "How do you handle trust issues that stem from past betrayals?",
      "What's your philosophy about trusting people to change and grow?",
      "How do you balance trusting your children with keeping them safe?",
      "What's your approach to institutional trust versus personal trust?",
      "How do you maintain faith in people's goodness despite betrayals and disappointments?"
    ]
  },

  // DAILY ESSENCE - Spiritual & Meditation Practices
  {
    category: 'daily_essence',
    subcategory: 'spiritual_practices',
    familyRoles: ['parent', 'grandparent'],
    emotionalDepth: 8,
    tags: ['spirituality', 'meditation', 'prayer', 'inner_peace', 'connection'],
    questions: [
      "What daily spiritual or contemplative practices bring you the most peace?",
      "How do you connect with something greater than yourself in ordinary moments?",
      "What's your approach to prayer or meditation that works best for you?",
      "How do you find sacred time and space in your busy daily life?",
      "What spiritual books, texts, or teachings resonate most deeply with you?",
      "How do you handle spiritual doubt or questions without losing your faith?",
      "What's your practice for finding inner calm during stressful periods?",
      "How do you use gratitude as a spiritual practice in daily life?",
      "What's your approach to finding meaning in mundane or difficult experiences?",
      "How do you connect with nature as part of your spiritual practice?",
      "What rituals or ceremonies mark important spiritual moments for you?",
      "How do you practice forgiveness as a spiritual discipline?",
      "What's your method for listening to your inner wisdom or intuition?",
      "How do you balance action with contemplation in your spiritual life?",
      "What's your approach to studying spiritual wisdom from different traditions?",
      "How do you find spiritual community while maintaining personal authenticity?",
      "What's your practice for dealing with suffering from a spiritual perspective?",
      "How do you cultivate compassion for difficult people in your life?",
      "What's your approach to spiritual service or helping others?",
      "How do you practice presence and mindfulness throughout your day?",
      "What's your method for spiritual reflection and self-examination?",
      "How do you handle spiritual dryness or periods when faith feels distant?",
      "What's your approach to integrating spiritual values with practical decisions?",
      "How do you find spiritual meaning in work and daily responsibilities?",
      "What's your practice for spiritual preparation before important events?",
      "How do you use solitude and silence as spiritual practices?",
      "What's your approach to spiritual guidance when facing major decisions?",
      "How do you practice spiritual acceptance of things you cannot change?",
      "What's your method for maintaining spiritual connection during busy seasons?",
      "How do you find spiritual renewal and refreshment when you're depleted?"
    ]
  },

  // FAMILY STORIES - Ancestors & Generational Wisdom
  {
    category: 'family_stories',
    subcategory: 'ancestral_wisdom',
    familyRoles: ['parent', 'grandparent'],
    emotionalDepth: 8,
    tags: ['ancestors', 'generations', 'wisdom', 'heritage', 'lineage'],
    questions: [
      "What wisdom did your great-grandparents pass down through the generations?",
      "Tell me about the strongest woman in our family's history and what made her remarkable.",
      "What do you know about ancestors who immigrated and the courage that required?",
      "Describe family members who overcame extraordinary hardships or challenges.",
      "What family sayings, mottos, or expressions have been passed down through generations?",
      "Tell me about ancestors who were known for their specific talents or abilities.",
      "What do you know about family members who made significant sacrifices for others?",
      "Describe the oldest family story you know and why it's been preserved.",
      "What patterns of strength or resilience run through our family line?",
      "Tell me about ancestors who were ahead of their time or unconventional.",
      "What family traits or characteristics seem to repeat across generations?",
      "Describe any family members who lived through historical events or periods.",
      "What do you know about ancestors who were particularly devout or spiritual?",
      "Tell me about family members who were known for their generosity or kindness.",
      "What family businesses or professions were passed down through generations?",
      "Describe ancestors who were known for their wisdom or good judgment.",
      "What do you know about family members who broke cycles or changed family patterns?",
      "Tell me about ancestors who were known for their creativity or artistic abilities.",
      "What family traditions originated with specific ancestors and why?",
      "Describe any family members who were known for their sense of humor or storytelling.",
      "What do you know about ancestors who faced discrimination or injustice?",
      "Tell me about family members who were known for their work ethic or integrity.",
      "What ancestral wisdom about relationships or love has been passed down?",
      "Describe family members who were known for their healing abilities or medical knowledge.",
      "What do you know about ancestors who were community leaders or activists?",
      "Tell me about family members who preserved culture or language through difficult times.",
      "What ancestral wisdom about raising children has influenced our family?",
      "Describe any family members who were known for their connection to the land or nature.",
      "What do you know about ancestors who showed exceptional courage in crisis?",
      "Tell me about the ancestral wisdom you most want to pass on to future generations."
    ]
  },

  // VALUES & BELIEFS - Environmental & Future Generations
  {
    category: 'values_beliefs',
    subcategory: 'environmental_future',
    familyRoles: ['parent', 'grandparent', 'mentor'],
    emotionalDepth: 7,
    tags: ['environment', 'future', 'sustainability', 'stewardship', 'responsibility'],
    questions: [
      "What's your philosophy about humanity's responsibility to care for the Earth?",
      "How do you balance current needs with preserving resources for future generations?",
      "What environmental changes have you witnessed in your lifetime and how do they affect you?",
      "How do you teach children to appreciate and protect the natural world?",
      "What's your approach to living sustainably without becoming overwhelmed by perfection?",
      "How do you handle environmental anxiety about the future your children will inherit?",
      "What's the most important thing about being a good steward of natural resources?",
      "How do you balance convenience with environmental responsibility in daily choices?",
      "What do you believe about the relationship between human progress and environmental protection?",
      "How do you find hope when environmental problems seem overwhelming?",
      "What's your philosophy about consuming less while still enjoying life's pleasures?",
      "How do you teach children about environmental responsibility without making them anxious?",
      "What's your approach to supporting environmental causes and making a difference?",
      "How do you handle disagreements with others about environmental issues?",
      "What's the most important environmental lesson you want to pass on to your children?",
      "How do you connect with nature in ways that nurture both you and the environment?",
      "What's your philosophy about technology's role in solving environmental problems?",
      "How do you balance individual environmental action with systemic change?",
      "What environmental traditions or practices do you hope your family continues?",
      "How do you find beauty and wonder in nature that inspires care and protection?",
      "What's your approach to environmental education and staying informed?",
      "How do you handle feelings of guilt or inadequacy about your environmental impact?",
      "What's your philosophy about the rights of future generations to a healthy planet?",
      "How do you teach children to make environmentally conscious choices independently?",
      "What's your approach to environmental activism that feels authentic to who you are?",
      "How do you maintain hope for environmental solutions despite current challenges?",
      "What's your philosophy about humanity's place in the broader web of life?",
      "How do you balance environmental concerns with other important values and priorities?",
      "What environmental legacy do you want to leave for your grandchildren?",
      "How do you find practical ways to live your environmental values in daily life?"
    ]
  },

  // MILESTONE MESSAGES - Health Crises & Recovery
  {
    category: 'milestone_messages',
    subcategory: 'health_recovery',
    familyRoles: ['parent', 'grandparent', 'spouse'],
    emotionalDepth: 10,
    tags: ['health', 'illness', 'recovery', 'healing', 'courage'],
    questions: [
      "If you're facing a serious illness, what do I want you to remember about your strength and courage?",
      "When you're in the hospital or recovering from surgery, what would I whisper to comfort you?",
      "If you receive a scary medical diagnosis, what perspective would I want you to maintain?",
      "When you're dealing with chronic pain or ongoing health challenges, how can I encourage you?",
      "If you're struggling with mental health issues, what would I want you to know about getting help?",
      "When you're afraid about a medical procedure, what would I tell you about facing fear with courage?",
      "If you're caring for someone else who is seriously ill, what support would I offer you?",
      "When you're making difficult decisions about medical treatment, what guidance would I give?",
      "If you're dealing with a disability or loss of function, what would I want you to remember?",
      "When you're feeling like your body has betrayed you, what would I tell you about self-compassion?",
      "If you're facing addiction or substance abuse recovery, what hope would I offer you?",
      "When you're supporting a family member through illness, what wisdom would help you?",
      "If you're dealing with fertility issues or pregnancy complications, what comfort would I provide?",
      "When you're aging and facing physical limitations, what would I want you to embrace?",
      "If you're making end-of-life decisions for yourself or others, what guidance would I give?",
      "When you're recovering from trauma or injury, what would I tell you about healing?",
      "If you're dealing with a mental health crisis, what would I want you to remember about hope?",
      "When you're facing genetic health risks, what would I tell you about courage and prevention?",
      "If you're caring for aging parents, what wisdom would I share about honoring their dignity?",
      "When you're dealing with health anxiety or medical fears, what peace would I offer you?",
      "If you're making healthcare decisions for your children, what guidance would I provide?",
      "When you're recovering from a major health setback, what would I tell you about resilience?",
      "If you're dealing with body image issues after illness, what would I want you to know?",
      "When you're advocating for your health needs, what strength would I remind you of?",
      "If you're facing a terminal diagnosis, what would I want you to know about living fully?",
      "When you're supporting others through grief and loss, what comfort would I offer?",
      "If you're dealing with healthcare costs or insurance issues, what perspective would help?",
      "When you're making lifestyle changes for better health, what encouragement would I give?",
      "If you're dealing with medical uncertainty or waiting for results, what peace would I provide?",
      "When you're celebrating recovery or improved health, what joy would I want to share with you?"
    ]
  },

  // EMOTIONAL WISDOM - Finding Inner Peace
  {
    category: 'emotional_wisdom',
    subcategory: 'inner_peace',
    familyRoles: ['parent', 'grandparent', 'mentor'],
    emotionalDepth: 9,
    tags: ['peace', 'serenity', 'calm', 'balance', 'centeredness'],
    questions: [
      "What's the secret to finding inner peace even when your external world is chaotic?",
      "How do you cultivate a sense of calm that isn't dependent on circumstances?",
      "What practices help you return to your center when you feel emotionally scattered?",
      "How do you find peace with decisions you've made that you can't change?",
      "What's your approach to letting go of things that disturb your inner peace?",
      "How do you maintain serenity when dealing with difficult or toxic people?",
      "What does it mean to accept what is while still working toward what could be?",
      "How do you find peace with uncertainty and the unknown future?",
      "What's your method for quieting your mind when it's racing with worries?",
      "How do you cultivate acceptance of your own limitations and imperfections?",
      "What's the difference between avoiding conflict and maintaining inner peace?",
      "How do you find peace with aging and the physical changes that come with time?",
      "What's your approach to forgiving others as a path to inner peace?",
      "How do you maintain equanimity during intense emotional experiences?",
      "What practices help you find peace with losses and things you cannot recover?",
      "How do you balance striving for goals with accepting where you are now?",
      "What's your method for finding peace in solitude versus peace in community?",
      "How do you handle regrets in a way that leads to peace rather than ongoing torment?",
      "What's your approach to finding peace with family members who are difficult?",
      "How do you cultivate inner stillness in a world full of noise and distraction?",
      "What does it mean to be at peace with your own mortality?",
      "How do you find peace with financial struggles or material limitations?",
      "What's your method for releasing control and finding peace with outcomes?",
      "How do you maintain inner peace when advocating for causes you believe in?",
      "What's your approach to finding peace with mistakes you've made in relationships?",
      "How do you cultivate peace through spiritual or contemplative practices?",
      "What's the secret to maintaining inner peace while caring for others' needs?",
      "How do you find peace with the gap between your ideals and reality?",
      "What practices help you maintain peace during times of major change?",
      "How do you teach others to find their own inner peace without forcing your methods on them?"
    ]
  },

  // FINAL MESSAGES - Spiritual & Afterlife Beliefs
  {
    category: 'final_messages',
    subcategory: 'spiritual_afterlife',
    familyRoles: ['parent', 'grandparent', 'spouse'],
    emotionalDepth: 10,
    tags: ['afterlife', 'eternity', 'spiritual', 'death', 'beyond'],
    questions: [
      "What do you believe happens after death, and how should that comfort your family?",
      "If there is an afterlife, what do you want your family to know about your continued presence?",
      "What spiritual beliefs about eternity and forever give you the most peace?",
      "How do you want your family to think about death - as an ending or a transition?",
      "What do you believe about souls, spirits, and the continuation of consciousness?",
      "If you could send signs or messages from beyond, what would you want your family to watch for?",
      "What role does faith play in how you face death and help your family face loss?",
      "How do you want your family to honor your spiritual beliefs after you're gone?",
      "What do you believe about reunion with loved ones who have died before you?",
      "How should your family find comfort in their own spiritual beliefs about death?",
      "What prayers, verses, or spiritual words bring you peace about mortality?",
      "If there's a heaven or spiritual realm, what do you imagine doing there?",
      "How do you want your family to balance grief with spiritual hope?",
      "What do you believe about guardian angels or protective spirits watching over loved ones?",
      "How should your family think about your spiritual journey continuing beyond physical death?",
      "What spiritual practices or rituals do you want your family to continue in your memory?",
      "If reincarnation is real, what do you hope to learn or accomplish in future lives?",
      "How do you want your family to understand the relationship between love and eternity?",
      "What do you believe about the purpose of this life in the context of spiritual existence?",
      "How should your family find strength in spiritual community after losing you?",
      "What do you want your family to know about your spiritual growth and transformation?",
      "If souls can communicate across the veil, how might you try to reach your family?",
      "How do you want your family to think about their own mortality and spiritual journey?",
      "What spiritual wisdom do you want to pass on about facing death without fear?",
      "How should your family find meaning in suffering through spiritual understanding?",
      "What do you believe about the eternal nature of family bonds and relationships?",
      "How do you want your family to prepare spiritually for their own eventual deaths?",
      "What spiritual legacy of faith, hope, and love do you want to leave behind?",
      "How should your family think about this life as part of a larger spiritual story?",
      "What do you want your family to know about finding God or divine presence in grief and loss?"
    ]
  },

  // PARENTAL WISDOM - Building Character
  {
    category: 'parental_wisdom',
    subcategory: 'character_building',
    familyRoles: ['parent', 'grandparent', 'mentor'],
    emotionalDepth: 9,
    tags: ['character', 'integrity', 'virtue', 'moral_development', 'ethics'],
    questions: [
      "What's the most important thing about developing strong moral character?",
      "How do you teach children the difference between right and wrong when situations are complex?",
      "What does it mean to have integrity even when no one is watching?",
      "How do you help children develop their own moral compass rather than just following rules?",
      "What's your approach to teaching kids about honesty even when truth is difficult?",
      "How do you model courage in facing ethical dilemmas and moral challenges?",
      "What's the secret to teaching children about justice and fairness?",
      "How do you help kids understand the importance of keeping their word and commitments?",
      "What's your approach to teaching children about compassion and empathy?",
      "How do you guide children through moral failures and help them learn from mistakes?",
      "What does it mean to teach children about responsibility for their actions and choices?",
      "How do you help kids develop the strength to stand up for what's right?",
      "What's your philosophy about teaching children to be humble yet confident?",
      "How do you teach kids about generosity and caring for those less fortunate?",
      "What's the most important thing about developing self-discipline and self-control?",
      "How do you help children understand the value of hard work and perseverance?",
      "What's your approach to teaching kids about respect for themselves and others?",
      "How do you guide children in developing wisdom and good judgment?",
      "What does it mean to teach children about loyalty while avoiding blind following?",
      "How do you help kids understand the importance of gratitude and appreciation?",
      "What's your philosophy about teaching children to forgive others and themselves?",
      "How do you teach kids about taking responsibility without carrying inappropriate guilt?",
      "What's the secret to helping children develop moral courage in peer situations?",
      "How do you guide children in understanding the relationship between freedom and responsibility?",
      "What's your approach to teaching kids about service to others and community?",
      "How do you help children develop the ability to admit when they're wrong?",
      "What does it mean to teach children about dignity and treating everyone with respect?",
      "How do you guide kids in developing patience and understanding with difficult people?",
      "What's the most important thing about teaching children to be trustworthy and reliable?",
      "How do you help children understand that strong character is built through daily choices?"
    ]
  },

  // LOVE & RELATIONSHIPS - Healing & Reconciliation
  {
    category: 'love_relationships',
    subcategory: 'healing_reconciliation',
    familyRoles: ['parent', 'grandparent', 'spouse'],
    emotionalDepth: 10,
    tags: ['healing', 'reconciliation', 'forgiveness', 'restoration', 'peace'],
    questions: [
      "What's the secret to healing relationships that have been deeply wounded?",
      "How do you know when a relationship can be restored versus when it's time to let go?",
      "What does true forgiveness look like, and how is it different from just forgetting?",
      "How do you approach someone you've hurt to make genuine amends?",
      "What's your philosophy about second chances and rebuilding trust after betrayal?",
      "How do you handle relationships with family members who have caused significant pain?",
      "What's the difference between reconciliation and just sweeping problems under the rug?",
      "How do you heal from emotional wounds while still keeping your heart open to love?",
      "What's your approach to apologizing in a way that promotes healing rather than just clearing your conscience?",
      "How do you maintain hope for reconciliation when relationships seem beyond repair?",
      "What does it mean to create healthy boundaries while still pursuing healing?",
      "How do you help others heal from wounds you've caused them?",
      "What's your philosophy about the role of time in healing relationship wounds?",
      "How do you handle ongoing relationships with people who won't acknowledge their harmful actions?",
      "What's the secret to healing from childhood wounds while maintaining love for your parents?",
      "How do you approach reconciliation when both parties have caused hurt?",
      "What does it mean to heal together as a couple after serious relationship damage?",
      "How do you know when someone is genuinely changed versus just saying what you want to hear?",
      "What's your approach to healing family rifts that have affected multiple generations?",
      "How do you balance protecting yourself with remaining open to relationship healing?",
      "What's the most important thing about professional help in healing serious relationship wounds?",
      "How do you handle the process of rebuilding intimacy after trust has been broken?",
      "What does it mean to heal from loss while honoring the relationship that was damaged?",
      "How do you approach healing when the other person has died before reconciliation was possible?",
      "What's your philosophy about healing relationships with people who have addiction or mental illness?",
      "How do you help children heal from wounds caused by family conflict or divorce?",
      "What's the secret to preventing past relationship wounds from damaging future relationships?",
      "How do you approach community or group healing when relationships have been damaged publicly?",
      "What does it mean to heal while maintaining realistic expectations about what the relationship can become?",
      "How do you find peace and healing even when full reconciliation isn't possible?"
    ]
  }
]

// Utility function to count questions in this file
export function getFinalLegacyQuestionCount(): number {
  return finalLegacyQuestions.reduce((total, template) => total + template.questions.length, 0)
}

// Function to get all questions across emotional depth levels
export function getQuestionsByEmotionalDepthRange(minDepth: number, maxDepth: number): string[] {
  return finalLegacyQuestions
    .filter(template => template.emotionalDepth >= minDepth && template.emotionalDepth <= maxDepth)
    .flatMap(template => template.questions)
}

// Function to export for seeding database
export function getAllFinalLegacyQuestions(): string[] {
  return finalLegacyQuestions.flatMap(template => template.questions)
}