// Mega expansion to reach 3,000+ legacy questions
import { LegacyQuestionTemplate } from './legacy-questions'

export const megaLegacyQuestions: LegacyQuestionTemplate[] = [
  // PARENTAL WISDOM - Life Transitions
  {
    category: 'parental_wisdom',
    subcategory: 'life_transitions',
    familyRoles: ['parent', 'grandparent'],
    emotionalDepth: 8,
    tags: ['transitions', 'change', 'growth', 'adaptation'],
    questions: [
      "How do you handle major life transitions without losing your sense of self?",
      "What's the secret to embracing change even when it's scary or unwanted?",
      "How do you know when it's time to close one chapter and start another?",
      "What's your approach to moving to a new place or starting over?",
      "How do you handle the loss of identity that comes with major life changes?",
      "What's the most important thing about adapting to new circumstances?",
      "How do you maintain relationships during major life transitions?",
      "What's your philosophy about timing and when to make big changes?",
      "How do you handle the grief that comes with leaving familiar things behind?",
      "What's your approach to building new routines and finding stability after change?",
      "How do you know the difference between growing pains and genuine problems?",
      "What's the most important thing about staying flexible as life evolves?",
      "How do you handle transitions that are forced on you versus ones you choose?",
      "What's your approach to helping family members through their own transitions?",
      "How do you maintain hope when transitions feel overwhelming or chaotic?",
      "What's the secret to finding opportunity in unwanted changes?",
      "How do you handle the financial stress that often comes with major transitions?",
      "What's your philosophy about burning bridges versus keeping doors open?",
      "How do you know when to fight for the old way versus embracing the new?",
      "What's your approach to managing anxiety during uncertain transitions?",
      "How do you handle transitions when you're responsible for other people too?",
      "What's the most important lesson about resilience during life changes?",
      "How do you maintain your values and priorities during disruptive transitions?",
      "What's your advice about preparing for transitions versus just going with the flow?",
      "How do you find your footing again after major life disruptions?",
      "What's the difference between adapting and compromising your core self?",
      "How do you handle the loneliness that can come with big life changes?",
      "What's your approach to learning new skills or ways of being during transitions?",
      "How do you maintain patience with yourself during adjustment periods?",
      "What's the most important thing about trusting the process of change?"
    ]
  },

  // FAMILY STORIES - Family Challenges & Overcoming
  {
    category: 'family_stories',
    subcategory: 'challenges_overcoming',
    familyRoles: ['parent', 'grandparent'],
    emotionalDepth: 8,
    tags: ['challenges', 'resilience', 'family_strength', 'overcoming'],
    questions: [
      "Tell me about the most difficult period our family went through and how we survived it.",
      "What family crisis brought us closer together instead of tearing us apart?",
      "Describe a time when our family had to choose between doing what was easy and doing what was right.",
      "What financial hardship did our family face and how did we get through it?",
      "Tell me about a time when our family had to stand together against outside pressure or criticism.",
      "What health crisis or medical emergency tested our family's strength?",
      "Describe how our family handled the loss of a family member or close friend.",
      "What misunderstanding or conflict within the family took time and effort to resolve?",
      "Tell me about a time when our family had to make a major sacrifice for one member.",
      "What natural disaster, accident, or emergency brought out the best in our family?",
      "Describe how our family dealt with someone's addiction, mental illness, or serious struggle.",
      "What legal trouble or serious mistake did a family member make and how did we handle it?",
      "Tell me about a time when our family's reputation or standing in the community was challenged.",
      "What economic opportunity did our family pursue that involved risk and uncertainty?",
      "Describe how our family handled someone's unexpected pregnancy, divorce, or major life change.",
      "What discrimination or unfair treatment did our family face and how did we respond?",
      "Tell me about a time when our family had to choose between loyalty and doing what was right.",
      "What business failure, job loss, or career setback affected the whole family?",
      "Describe how our family supported someone through depression, grief, or emotional crisis.",
      "What move, relocation, or major change did our family navigate together?",
      "Tell me about a time when our family had to confront someone's dishonesty or betrayal.",
      "What generational conflict or difference of values did our family work through?",
      "Describe how our family handled someone's serious illness or disability.",
      "What community crisis or social issue galvanized our family to take action?",
      "Tell me about the most important lesson our family learned from facing adversity together.",
      "What strength or quality did our family discover about itself during tough times?",
      "Describe how our family's faith, values, or principles were tested and strengthened.",
      "What support did our family receive from others during our most difficult time?",
      "Tell me about how our family emerged different but stronger from a major challenge.",
      "What wisdom did our family gain that we want to pass on to future generations?"
    ]
  },

  // LOVE & RELATIONSHIPS - Conflict Resolution
  {
    category: 'love_relationships',
    subcategory: 'conflict_resolution',
    familyRoles: ['parent', 'grandparent', 'spouse'],
    emotionalDepth: 7,
    tags: ['conflict', 'resolution', 'communication', 'peace'],
    questions: [
      "What's your approach to handling disagreements without damaging relationships?",
      "How do you fight fair when emotions are running high?",
      "What's the difference between resolving conflict and just avoiding it?",
      "How do you know when to stand your ground versus when to compromise?",
      "What's your strategy for de-escalating heated arguments or confrontations?",
      "How do you handle conflicts when both sides have valid points?",
      "What's your approach to apologizing sincerely and effectively?",
      "How do you address underlying issues instead of just surface disagreements?",
      "What's your philosophy about forgiveness and letting go of grudges?",
      "How do you handle conflicts with people who don't want to resolve them?",
      "What's your approach to mediating conflicts between other people?",
      "How do you maintain respect for someone during a disagreement?",
      "What's the most important thing about timing when addressing conflicts?",
      "How do you separate the person from the problem during disputes?",
      "What's your strategy for finding win-win solutions to conflicts?",
      "How do you handle your own anger or hurt feelings during conflicts?",
      "What's your approach to rebuilding trust after a serious disagreement?",
      "How do you know when a conflict is worth pursuing versus when to let it go?",
      "What's your strategy for preventing small disagreements from becoming big fights?",
      "How do you handle conflicts that involve deeply held values or beliefs?",
      "What's your approach to conflicts where there's no clear right or wrong?",
      "How do you maintain family unity when family members are in conflict?",
      "What's your philosophy about public versus private conflict resolution?",
      "How do you handle conflicts with authority figures or people in power?",
      "What's your approach to healing relationships after painful conflicts?",
      "How do you teach children to handle conflicts constructively?",
      "What's the most important lesson you've learned about making peace?",
      "How do you balance being honest about problems with being diplomatic?",
      "What's your strategy for staying calm and rational during emotional conflicts?",
      "How do you know when professional help is needed to resolve serious conflicts?"
    ]
  },

  // VALUES & BELIEFS - Life Philosophy
  {
    category: 'values_beliefs',
    subcategory: 'life_philosophy',
    familyRoles: ['parent', 'grandparent', 'mentor'],
    emotionalDepth: 9,
    tags: ['philosophy', 'meaning', 'purpose', 'wisdom', 'perspective'],
    questions: [
      "What do you believe is the fundamental purpose of human existence?",
      "How do you find meaning in both joyful and painful experiences?",
      "What's your philosophy about fate versus free will in shaping our lives?",
      "How do you define a life well-lived?",
      "What do you believe about the nature of good and evil in the world?",
      "How do you handle the fact that life is often unfair or random?",
      "What's your perspective on suffering and why it exists in the world?",
      "How do you balance acceptance of what is with working to change what can be changed?",
      "What do you believe about human nature - are people fundamentally good or bad?",
      "How do you find hope and optimism in a world with so much darkness?",
      "What's your philosophy about the relationship between individual happiness and responsibility to others?",
      "How do you handle existential questions about why we're here?",
      "What do you believe about the interconnectedness of all people and things?",
      "How do you find peace with the temporary nature of life and all we love?",
      "What's your perspective on the role of struggle and challenge in personal growth?",
      "How do you balance living in the present with planning for the future?",
      "What do you believe about the possibility of changing the world for the better?",
      "How do you handle the paradoxes and contradictions inherent in life?",
      "What's your philosophy about the relationship between knowledge and wisdom?",
      "How do you find beauty and wonder even in difficult circumstances?",
      "What do you believe about the importance of legacy and how we're remembered?",
      "How do you balance self-care with service to others and the greater good?",
      "What's your perspective on the role of chance and coincidence in life?",
      "How do you find meaning in ordinary, everyday moments?",
      "What do you believe about the possibility of redemption and second chances?",
      "How do you handle questions that don't have clear answers?",
      "What's your philosophy about the relationship between material success and spiritual fulfillment?",
      "How do you balance idealism with realism in how you approach life?",
      "What do you believe about the importance of truth versus kindness?",
      "How do you find wisdom and guidance when facing life's biggest questions?"
    ]
  },

  // MILESTONE MESSAGES - Career & Professional Life
  {
    category: 'milestone_messages',
    subcategory: 'career_professional',
    familyRoles: ['parent', 'grandparent', 'mentor'],
    emotionalDepth: 7,
    tags: ['career', 'work', 'professional', 'success', 'achievement'],
    questions: [
      "What do you want me to remember about following my passion versus being practical in my career?",
      "If I'm struggling to find my career path, what guidance would you give me?",
      "When I get my first real job, what do you want me to know about workplace dynamics?",
      "What advice do you have for me about building professional relationships and networking?",
      "If I'm facing a major career decision, what factors should I consider most carefully?",
      "What do you want me to know about handling workplace conflict and office politics?",
      "When I achieve a major professional milestone, what perspective should I maintain?",
      "What's your advice about balancing career ambition with family responsibilities?",
      "If I'm dealing with a difficult boss or coworkers, what approach would you recommend?",
      "What do you want me to remember about maintaining integrity in professional settings?",
      "When I'm feeling stuck or unfulfilled in my career, what should I do?",
      "What's your advice about taking calculated risks versus playing it safe professionally?",
      "If I'm considering starting my own business, what wisdom would you share?",
      "What do you want me to know about managing money and building financial security?",
      "When I face professional setbacks or failures, how should I respond?",
      "What's your advice about continuing education and staying relevant in my field?",
      "If I'm struggling with work-life balance, what perspective would help me?",
      "What do you want me to remember about treating all people with respect regardless of their position?",
      "When I'm negotiating salary or promotions, what approach should I take?",
      "What's your advice about building a reputation and personal brand professionally?",
      "If I'm considering a major career change, what questions should I ask myself?",
      "What do you want me to know about leadership and managing other people?",
      "When I'm facing retirement or career transitions, what wisdom would guide me?",
      "What's your advice about finding mentors and being a mentor to others?",
      "What do you want me to remember about defining success on my own terms?",
      "If I'm dealing with professional jealousy or competition, how should I handle it?",
      "What's your guidance about speaking up for myself and advocating for what I deserve?",
      "When I'm making decisions that affect other people's jobs or livelihoods, what should I remember?",
      "What do you want me to know about the importance of continuous learning and adaptation?",
      "What's your advice about leaving a positive professional legacy?"
    ]
  },

  // EMOTIONAL WISDOM - Joy & Gratitude
  {
    category: 'emotional_wisdom',
    subcategory: 'joy_gratitude',
    familyRoles: ['parent', 'grandparent'],
    emotionalDepth: 7,
    tags: ['joy', 'gratitude', 'happiness', 'appreciation', 'celebration'],
    questions: [
      "What's the secret to finding joy even during difficult periods of life?",
      "How do you cultivate genuine gratitude without just going through the motions?",
      "What's the difference between happiness and joy, and which is more important?",
      "How do you celebrate life's victories without becoming arrogant or taking things for granted?",
      "What's your approach to appreciating ordinary moments and everyday blessings?",
      "How do you maintain a sense of wonder and amazement about life?",
      "What's the most important thing about sharing your joy with others?",
      "How do you handle guilt about being happy when others are suffering?",
      "What's your philosophy about the relationship between gratitude and contentment?",
      "How do you find reasons to be grateful even when life is challenging?",
      "What's your approach to celebrating other people's successes and good fortune?",
      "How do you maintain optimism without being naive about life's difficulties?",
      "What's the secret to laughing and finding humor even in tough situations?",
      "How do you appreciate what you have while still working toward goals?",
      "What's your approach to creating joyful traditions and celebrations?",
      "How do you handle seasonal depression or times when joy feels elusive?",
      "What's the most important thing about teaching children to find and create joy?",
      "How do you balance realistic expectations with maintaining a joyful outlook?",
      "What's your philosophy about the role of material things in creating happiness?",
      "How do you find joy in service to others and making a difference?",
      "What's your approach to dealing with people who seem to drain your joy?",
      "How do you maintain gratitude for your health when dealing with physical challenges?",
      "What's the secret to finding beauty and joy in unexpected places?",
      "How do you handle the guilt that sometimes comes with experiencing joy?",
      "What's your approach to preserving joyful memories and experiences?",
      "How do you find joy in solitude and your own company?",
      "What's the most important thing about spreading joy and positivity to others?",
      "How do you maintain a sense of playfulness and fun as you age?",
      "What's your philosophy about the relationship between gratitude and resilience?",
      "How do you create an environment where joy can flourish for yourself and your family?"
    ]
  },

  // DAILY ESSENCE - Creative Expression & Interests
  {
    category: 'daily_essence',
    subcategory: 'creative_interests',
    familyRoles: ['parent', 'grandparent', 'spouse'],
    emotionalDepth: 6,
    tags: ['creativity', 'hobbies', 'interests', 'passion', 'expression'],
    questions: [
      "What creative activities or hobbies bring you the most satisfaction?",
      "How do you express your creativity when you're not naturally artistic?",
      "What's something you've always wanted to learn or try but haven't yet?",
      "How do you make time for activities that feed your soul and creativity?",
      "What's your favorite way to spend free time when you have no obligations?",
      "How do you handle creative blocks or times when inspiration feels stuck?",
      "What skills or talents do you have that you're most proud of?",
      "How do you balance productive activities with pure enjoyment and play?",
      "What's your approach to learning new skills or pursuing new interests?",
      "How do you share your creative interests with family and friends?",
      "What creative project or accomplishment gives you lasting satisfaction?",
      "How do you handle perfectionism when pursuing creative activities?",
      "What's your philosophy about the value of hobbies and non-productive activities?",
      "How do you find inspiration and ideas for creative projects?",
      "What creative activity helps you process emotions or stress?",
      "How do you balance multiple interests and avoid spreading yourself too thin?",
      "What's your approach to displaying or sharing your creative work?",
      "How do you handle criticism or feedback about your creative expressions?",
      "What creative tradition or activity do you hope your family continues?",
      "How do you find creative communities or people who share your interests?",
      "What's the most ambitious creative project you've ever undertaken?",
      "How do you maintain motivation for long-term creative goals?",
      "What creative activity connects you most deeply to your authentic self?",
      "How do you balance perfectionism with enjoying the creative process?",
      "What's your advice about pursuing creative interests regardless of talent level?",
      "How do you use creativity to connect with and understand other people?",
      "What creative legacy do you want to leave for your family?",
      "How do you find time and space for creativity in a busy life?",
      "What's the most important thing about following your creative curiosity?",
      "How do you celebrate and appreciate your own creative growth and progress?"
    ]
  },

  // FINAL MESSAGES - Hopes & Dreams for Future
  {
    category: 'final_messages',
    subcategory: 'hopes_dreams_future',
    familyRoles: ['parent', 'grandparent'],
    emotionalDepth: 10,
    tags: ['hope', 'dreams', 'future', 'wishes', 'legacy'],
    questions: [
      "What hopes do you have for the world your children and grandchildren will inherit?",
      "What dreams do you have for each of your children that you may not live to see fulfilled?",
      "What do you hope your family learns from the challenges and changes the world is facing?",
      "What technological or social changes do you hope will make life better for future generations?",
      "What family traditions do you hope will continue for generations to come?",
      "What do you hope your descendants will remember about our family's values and character?",
      "What problems in the world do you hope your children will help solve?",
      "What adventures or experiences do you hope your family will have?",
      "What do you hope your children teach their own children about love and life?",
      "What scientific discoveries or human achievements do you hope to see from beyond?",
      "What do you hope your family contributes to making the world a better place?",
      "What personal growth and healing do you hope each family member experiences?",
      "What do you hope your children never have to face or experience?",
      "What freedoms and opportunities do you hope remain available to future generations?",
      "What do you hope your family learns about forgiveness, redemption, and second chances?",
      "What environmental improvements do you hope the world makes for your grandchildren?",
      "What do you hope your descendants understand about the importance of education and learning?",
      "What cultural or artistic achievements do you hope your family appreciates and supports?",
      "What do you hope your children never lose their sense of wonder and curiosity about?",
      "What forms of connection and community do you hope remain strong in the future?",
      "What do you hope your family remembers about the importance of compassion and kindness?",
      "What innovations in healthcare do you hope benefit your children as they age?",
      "What do you hope your descendants learn about resilience and overcoming adversity?",
      "What aspects of human nature do you hope continue to flourish in future generations?",
      "What do you hope your family's love story teaches others about commitment and partnership?",
      "What global challenges do you hope humanity unites to address and solve?",
      "What do you hope your children's children learn from the stories of our family's journey?",
      "What wisdom do you hope gets passed down through generations of our family?",
      "What do you hope your legacy inspires others to do or become?",
      "What final blessing or prayer do you offer for all the generations that will come after you?"
    ]
  }
]

// Utility function to count total questions
export function getMegaLegacyQuestionCount(): number {
  return megaLegacyQuestions.reduce((total, template) => total + template.questions.length, 0)
}