# Prometheus Configuration for Echoes of Me
# Local development monitoring setup

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'echosofme-local'
    environment: 'development'

# Alertmanager configuration (optional for local dev)
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Rule files (optional for local dev)
rule_files: []

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    metrics_path: /metrics

  # Next.js Application (if metrics endpoint exists)
  - job_name: 'echosofme-app'
    static_configs:
      - targets: ['app:3000']
    scrape_interval: 30s
    metrics_path: /api/metrics
    scrape_timeout: 10s
    # Only scrape if the endpoint exists
    honor_labels: true

  # PostgreSQL metrics (using postgres_exporter if added)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s
    metrics_path: /metrics

  # Redis metrics (using redis_exporter if added)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s
    metrics_path: /metrics

  # Nginx metrics (if enabled)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:8080']
    scrape_interval: 30s
    metrics_path: /nginx_status

# Storage configuration
storage:
  tsdb:
    path: /prometheus
    retention.time: 15d
    retention.size: 1GB

# Remote write configuration (for cloud migration)
# remote_write:
#   - url: "https://your-remote-prometheus/api/v1/write"
#     basic_auth:
#       username: "your-username"
#       password: "your-password"