// Massive final batch to exceed 3,000+ legacy questions
import { LegacyQuestionTemplate } from './legacy-questions'

export const massiveLegacyQuestions: LegacyQuestionTemplate[] = [
  // PARENTAL WISDOM - Teaching Independence
  {
    category: 'parental_wisdom',
    subcategory: 'teaching_independence',
    familyRoles: ['parent', 'grandparent'],
    emotionalDepth: 7,
    tags: ['independence', 'self_reliance', 'confidence', 'capability'],
    questions: [
      "What's the secret to raising children who are independent but still connected to family?",
      "How do you teach kids to solve problems on their own before asking for help?",
      "What's your approach to letting children fail safely so they learn resilience?",
      "How do you balance protecting children with letting them experience natural consequences?",
      "What's the most important life skill every child should master before becoming an adult?",
      "How do you teach children to trust their own judgment and decision-making abilities?",
      "What's your method for gradually increasing children's freedom and responsibility?",
      "How do you help kids develop confidence without becoming arrogant or entitled?",
      "What's your approach to teaching children about money management and financial responsibility?",
      "How do you teach kids to advocate for themselves and speak up when needed?",
      "What's the secret to raising children who can handle disappointment and setbacks?",
      "How do you help children develop their own moral compass separate from parental rules?",
      "What's your method for teaching kids to be good friends and relationship partners?",
      "How do you teach children to take calculated risks without being reckless?",
      "What's your approach to helping kids find their own passions and interests?",
      "How do you teach children to handle authority figures and institutional relationships?",
      "What's the most important thing about teaching kids to learn from their mistakes?",
      "How do you help children develop emotional regulation and self-control?",
      "What's your method for teaching kids to be helpful without being taken advantage of?",
      "How do you teach children to stand up for themselves and others who need support?",
      "What's your approach to helping kids develop critical thinking and media literacy?",
      "How do you teach children to handle peer pressure and social influence?",
      "What's the secret to raising kids who are leaders rather than just followers?",
      "How do you help children develop their own spiritual or philosophical beliefs?",
      "What's your method for teaching kids to handle success and recognition with humility?",
      "How do you teach children to be culturally aware and respectful of differences?",
      "What's your approach to helping kids develop healthy habits and self-care routines?",
      "How do you teach children to be good citizens and contribute to their community?",
      "What's the most important thing about preparing kids for the realities of adult life?",
      "How do you help children maintain their sense of wonder while developing practical skills?",
      "What's your method for teaching kids to be both independent and collaborative?",
      "How do you teach children to handle technology responsibly and maintain privacy?",
      "What's your approach to helping kids develop their own unique identity and voice?",
      "How do you teach children to be resilient without becoming callous or uncaring?",
      "What's the secret to raising kids who can adapt to change and uncertainty?",
      "How do you help children develop the confidence to pursue their dreams?",
      "What's your method for teaching kids to be honest with themselves about their strengths and weaknesses?",
      "How do you teach children to maintain hope and optimism even during difficult times?",
      "What's your approach to helping kids develop wisdom and good judgment?",
      "How do you teach children that independence means being responsible for their impact on others?"
    ]
  },

  // DAILY ESSENCE - Health & Wellness Philosophy
  {
    category: 'daily_essence',
    subcategory: 'health_wellness_philosophy',
    familyRoles: ['parent', 'grandparent'],
    emotionalDepth: 6,
    tags: ['health', 'wellness', 'fitness', 'nutrition', 'longevity'],
    questions: [
      "What's your philosophy about taking care of your body and maintaining good health?",
      "How do you balance enjoying food with eating nutritiously and maintaining healthy weight?",
      "What's your approach to exercise and physical activity that you can sustain long-term?",
      "How do you handle aging and physical changes with grace and acceptance?",
      "What's your method for managing stress before it impacts your physical health?",
      "How do you maintain mental health and emotional wellbeing as part of overall wellness?",
      "What's your approach to preventive healthcare and regular medical checkups?",
      "How do you balance medical interventions with natural healing and wellness practices?",
      "What's your philosophy about sleep and rest as essential components of health?",
      "How do you handle chronic pain or ongoing health challenges without losing hope?",
      "What's your method for staying motivated to maintain healthy habits?",
      "How do you balance health goals with enjoying life's pleasures and social activities?",
      "What's your approach to supplements, vitamins, and alternative health practices?",
      "How do you handle health anxiety and medical fears without becoming obsessed?",
      "What's your philosophy about the connection between mental and physical health?",
      "How do you maintain healthy habits during busy periods or stressful times?",
      "What's your method for recovering from illness or injury with patience?",
      "How do you balance individual health needs with family responsibilities?",
      "What's your approach to alcohol, smoking, and other substances that affect health?",
      "How do you handle genetic health risks and family medical history?",
      "What's your philosophy about body image and accepting your physical appearance?",
      "How do you maintain energy and vitality as you age?",
      "What's your method for making healthcare decisions and choosing medical providers?",
      "How do you balance health consciousness with not becoming overly restrictive?",
      "What's your approach to teaching children about health and wellness?",
      "How do you handle health setbacks and medical diagnoses with resilience?",
      "What's your philosophy about the role of community and relationships in health?",
      "How do you maintain hope and quality of life even with health limitations?",
      "What's your method for advocating for your health needs in medical settings?",
      "How do you balance current health practices with preparing for aging and end-of-life care?",
      "What's your approach to holistic wellness that includes spiritual and emotional health?",
      "How do you handle health insurance, medical costs, and healthcare system navigation?",
      "What's your philosophy about work-life balance and its impact on health?",
      "How do you maintain healthy boundaries and relationships for overall wellbeing?",
      "What's your method for staying informed about health without becoming overwhelmed by information?",
      "How do you balance health goals with accepting your body's limitations?",
      "What's your approach to recovery and healing from trauma or emotional wounds?",
      "How do you maintain healthy habits while traveling or during routine disruptions?",
      "What's your philosophy about the relationship between purpose, meaning, and physical health?",
      "How do you model healthy living for your children and family without being preachy?"
    ]
  },

  // LOVE & RELATIONSHIPS - Dealing with Difficult People
  {
    category: 'love_relationships',
    subcategory: 'difficult_people',
    familyRoles: ['parent', 'grandparent', 'mentor'],
    emotionalDepth: 8,
    tags: ['difficult_people', 'boundaries', 'conflict', 'tolerance', 'patience'],
    questions: [
      "What's your approach to maintaining relationships with people who are consistently difficult?",
      "How do you set boundaries with family members who are toxic or harmful?",
      "What's your method for dealing with people who are chronically negative or pessimistic?",
      "How do you handle relationships with people who have untreated mental illness or addiction?",
      "What's your approach to dealing with narcissistic or self-centered people?",
      "How do you maintain your own emotional health when dealing with manipulative people?",
      "What's your method for handling people who are always critical or judgmental?",
      "How do you deal with family members who create drama or chaos?",
      "What's your approach to relationships with people who refuse to take responsibility?",
      "How do you handle people who are dishonest or untrustworthy?",
      "What's your method for dealing with passive-aggressive behavior?",
      "How do you maintain compassion for difficult people without enabling their behavior?",
      "What's your approach to handling people who are verbally or emotionally abusive?",
      "How do you deal with people who are jealous or competitive in unhealthy ways?",
      "What's your method for handling relationships where you feel constantly drained?",
      "How do you set limits with people who don't respect your boundaries?",
      "What's your approach to dealing with people who gossip or spread negativity?",
      "How do you handle family gatherings when difficult people will be present?",
      "What's your method for responding to people who are always angry or hostile?",
      "How do you deal with people who try to control or micromanage others?",
      "What's your approach to handling people who are chronically unreliable?",
      "How do you maintain your values when dealing with people who have different moral standards?",
      "What's your method for dealing with people who are prejudiced or discriminatory?",
      "How do you handle relationships with people who have different political or religious views?",
      "What's your approach to dealing with people who are emotionally immature?",
      "How do you maintain professional relationships with difficult colleagues or bosses?",
      "What's your method for handling people who take credit for others' work?",
      "How do you deal with people who are chronically pessimistic about your goals or dreams?",
      "What's your approach to handling people who violate your trust repeatedly?",
      "How do you know when to end a relationship versus when to keep trying?",
      "What's your method for protecting your children from difficult or harmful family members?",
      "How do you handle guilt about limiting contact with difficult people?",
      "What's your approach to forgiveness when people continue to hurt you?",
      "How do you maintain hope that difficult people can change while protecting yourself?",
      "What's your method for dealing with difficult people in community or social settings?",
      "How do you handle the stress and anxiety that difficult relationships can cause?",
      "What's your approach to seeking support when dealing with particularly challenging people?",
      "How do you maintain your own integrity when others behave badly?",
      "What's your method for teaching children to handle difficult people appropriately?",
      "How do you balance being patient with difficult people while maintaining your own wellbeing?"
    ]
  },

  // FAMILY STORIES - Adventures & Travel
  {
    category: 'family_stories',
    subcategory: 'adventures_travel',
    familyRoles: ['parent', 'grandparent'],
    emotionalDepth: 6,
    tags: ['travel', 'adventure', 'exploration', 'memories', 'experience'],
    questions: [
      "Tell me about the most adventurous trip your family ever took together.",
      "What's the story of a vacation that didn't go as planned but became a great memory?",
      "Describe the most beautiful place you've ever visited and why it moved you.",
      "What family camping trip or outdoor adventure do you remember most fondly?",
      "Tell me about a time when you got lost while traveling and what happened.",
      "What's the funniest travel mishap your family ever experienced?",
      "Describe the most luxurious or special vacation you ever took.",
      "What road trip taught you the most about your family or yourself?",
      "Tell me about a place you visited that changed your perspective on life.",
      "What's the story of a spontaneous adventure or unplanned trip?",
      "Describe the most challenging travel experience you overcame as a family.",
      "What international travel experience opened your eyes to different cultures?",
      "Tell me about a place you visited that you would want to return to.",
      "What's the story of a trip where you met interesting or memorable people?",
      "Describe a travel experience that taught you something important about yourself.",
      "What family tradition around travel or vacations was most important to you?",
      "Tell me about the first airplane ride or major trip you ever took.",
      "What's the story of a trip you took to visit relatives or family history?",
      "Describe a travel experience where you had to be brave or face your fears.",
      "What adventure or trip do you wish you had taken but never did?",
      "Tell me about a place you visited that had special spiritual or emotional significance.",
      "What's the story of a trip where the journey was more memorable than the destination?",
      "Describe a travel experience that brought your family closer together.",
      "What place did you visit that you would want your children to see?",
      "Tell me about a local adventure or day trip that was surprisingly wonderful.",
      "What's the story of a trip where you learned something new about your partner or children?",
      "Describe a travel experience that was completely outside your comfort zone.",
      "What place did you visit that made you feel most connected to nature?",
      "Tell me about a cultural or historical site that made a lasting impression on you.",
      "What's the story of your honeymoon or a special romantic trip?",
      "Describe a travel experience that was physically challenging but rewarding.",
      "What place did you visit that you never expected to love but did?",
      "Tell me about a trip where you discovered something unexpected about a destination.",
      "What's the story of the longest journey you ever took?",
      "Describe a travel experience that helped you appreciate home more.",
      "What adventure would you encourage your children to take?",
      "Tell me about a place you visited that felt like a second home.",
      "What's the story of a trip that marked an important transition in your life?",
      "Describe a travel experience that created lasting friendships or connections.",
      "What place or adventure represents the best of your family's shared experiences?"
    ]
  },

  // VALUES & BELIEFS - Science & Knowledge
  {
    category: 'values_beliefs',
    subcategory: 'science_knowledge',
    familyRoles: ['parent', 'grandparent', 'mentor'],
    emotionalDepth: 6,
    tags: ['science', 'knowledge', 'learning', 'truth', 'discovery'],
    questions: [
      "What's your philosophy about the relationship between science and faith or spirituality?",
      "How do you balance scientific skepticism with remaining open to possibilities?",
      "What scientific discovery or advancement has most fascinated or inspired you?",
      "How do you approach conflicting scientific studies or changing scientific understanding?",
      "What's your view on the importance of scientific literacy in everyday life?",
      "How do you handle scientific or medical information that conflicts with personal beliefs?",
      "What's your approach to teaching children about science and critical thinking?",
      "How do you balance respect for traditional knowledge with scientific understanding?",
      "What's your philosophy about the role of science in solving humanity's problems?",
      "How do you handle uncertainty when scientific understanding is still evolving?",
      "What's your approach to evaluating scientific claims and avoiding misinformation?",
      "How do you balance the benefits of technology with concerns about its impact?",
      "What's your view on the ethical responsibilities of scientists and researchers?",
      "How do you approach topics where science and politics intersect?",
      "What's your philosophy about the limits of scientific knowledge and understanding?",
      "How do you handle situations where scientific evidence challenges common beliefs?",
      "What's your approach to medical decisions when scientific evidence is mixed?",
      "How do you balance scientific understanding with intuition and personal experience?",
      "What's your view on the importance of funding scientific research and education?",
      "How do you approach environmental issues from a scientific perspective?",
      "What's your philosophy about the relationship between scientific progress and social change?",
      "How do you handle discussions about science with people who have different views?",
      "What's your approach to understanding complex scientific issues as a non-expert?",
      "How do you balance healthy skepticism with trust in scientific institutions?",
      "What's your view on the role of science in understanding human nature and behavior?",
      "How do you approach genetic information and personalized medicine?",
      "What's your philosophy about the pace of technological and scientific change?",
      "How do you handle ethical dilemmas raised by scientific and medical advances?",
      "What's your approach to teaching children about the scientific method and evidence-based thinking?",
      "How do you balance wonder and curiosity with practical scientific knowledge?",
      "What's your view on the responsibility of individuals to understand basic science?",
      "How do you approach scientific questions that don't have clear answers yet?",
      "What's your philosophy about the relationship between scientific knowledge and wisdom?",
      "How do you handle cognitive biases when evaluating scientific information?",
      "What's your approach to participating in scientific research or studies?",
      "How do you balance scientific understanding with emotional and spiritual needs?",
      "What's your view on the importance of diverse perspectives in scientific research?",
      "How do you approach mental health from both scientific and personal perspectives?",
      "What's your philosophy about the role of science in education and child development?",
      "How do you maintain intellectual humility while developing scientific understanding?"
    ]
  },

  // EMOTIONAL WISDOM - Handling Success & Achievement
  {
    category: 'emotional_wisdom',
    subcategory: 'success_achievement',
    familyRoles: ['parent', 'grandparent', 'mentor'],
    emotionalDepth: 7,
    tags: ['success', 'achievement', 'recognition', 'accomplishment', 'pride'],
    questions: [
      "What's the secret to handling success with grace and humility?",
      "How do you celebrate achievements without becoming arrogant or entitled?",
      "What's your approach to maintaining perspective when receiving recognition or praise?",
      "How do you handle the pressure that often comes with success?",
      "What's your method for staying grounded during periods of achievement?",
      "How do you balance confidence from success with continued openness to learning?",
      "What's your approach to sharing credit and acknowledging others who helped you succeed?",
      "How do you handle jealousy or resentment from others about your success?",
      "What's your method for using success as motivation for greater service to others?",
      "How do you maintain relationships when success changes your circumstances?",
      "What's your approach to setting new goals after achieving major objectives?",
      "How do you handle the fear of losing what you've gained through success?",
      "What's your method for defining success on your own terms rather than society's?",
      "How do you balance enjoying your achievements with continued striving?",
      "What's your approach to teaching children about success and achievement?",
      "How do you handle success that comes at the expense of other life priorities?",
      "What's your method for maintaining authenticity during periods of recognition?",
      "How do you balance individual achievement with team or family success?",
      "What's your approach to handling media attention or public recognition?",
      "How do you maintain motivation after achieving something you worked toward for years?",
      "What's your method for handling success that feels undeserved or accidental?",
      "How do you balance celebrating success with preparing for future challenges?",
      "What's your approach to financial success and the responsibilities it brings?",
      "How do you handle the loneliness that can sometimes come with success?",
      "What's your method for maintaining empathy for others who haven't achieved similar success?",
      "How do you balance professional success with personal fulfillment and happiness?",
      "What's your approach to handling criticism even when you're successful?",
      "How do you maintain family relationships when career success demands time and energy?",
      "What's your method for using success to create opportunities for others?",
      "How do you handle the responsibility of being a role model after achieving recognition?",
      "What's your approach to continuing personal growth even after external validation?",
      "How do you balance the confidence that comes from success with appropriate humility?",
      "What's your method for handling success in one area while struggling in others?",
      "How do you maintain perspective about what success really means in the context of a whole life?",
      "What's your approach to helping others achieve success without creating competition?",
      "How do you handle the guilt that can sometimes come with having more than others?",
      "What's your method for staying connected to your values during periods of achievement?",
      "How do you balance the desire for more success with gratitude for current accomplishments?",
      "What's your approach to retirement or stepping back after a successful career?",
      "How do you define and measure success in relationships, parenting, and personal growth?"
    ]
  },

  // MILESTONE MESSAGES - Spiritual & Religious Ceremonies
  {
    category: 'milestone_messages',
    subcategory: 'spiritual_religious_ceremonies',
    familyRoles: ['parent', 'grandparent'],
    emotionalDepth: 9,
    tags: ['spiritual', 'religious', 'ceremony', 'faith', 'meaningful'],
    questions: [
      "What do you want me to know about the spiritual significance of baptism, confirmation, or other religious ceremonies?",
      "If I'm questioning my faith during adolescence or young adulthood, what wisdom would you share?",
      "What do you want me to understand about the importance of spiritual community and religious participation?",
      "When I'm preparing for marriage in a religious ceremony, what spiritual counsel would you offer?",
      "What do you want me to know about raising children with faith while respecting their individual journey?",
      "If I'm considering ordination or deeper religious commitment, what guidance would you provide?",
      "What do you want me to understand about prayer and how to maintain a spiritual practice?",
      "When I'm facing a crisis of faith or spiritual doubt, what would you tell me about the journey?",
      "What do you want me to know about forgiveness from both human and divine perspectives?",
      "If I'm choosing a different faith path than you, what love and acceptance would you express?",
      "What do you want me to understand about the relationship between good works and faith?",
      "When I'm preparing for religious leadership or spiritual service, what wisdom would you share?",
      "What do you want me to know about finding God or spiritual meaning in everyday life?",
      "If I'm struggling with religious rules or doctrine, what freedom would you encourage?",
      "What do you want me to understand about the balance between individual spirituality and organized religion?",
      "When I'm facing death or mortality, what spiritual comfort would you offer?",
      "What do you want me to know about how faith has sustained you through difficult times?",
      "If I'm considering a pilgrimage or spiritual journey, what blessings would you give?",
      "What do you want me to understand about religious tolerance and respecting other faiths?",
      "When I'm teaching my own children about faith, what approach would you recommend?",
      "What do you want me to know about the relationship between science and spiritual belief?",
      "If I'm participating in interfaith relationships or marriages, what wisdom would you share?",
      "What do you want me to understand about service and charity as expressions of faith?",
      "When I'm studying religious texts or theology, what perspective would guide me?",
      "What do you want me to know about finding peace and contentment through spiritual practice?",
      "If I'm struggling with guilt or shame about past actions, what spiritual healing would you offer?",
      "What do you want me to understand about the role of ritual and ceremony in spiritual life?",
      "When I'm making ethical decisions, what spiritual principles should guide me?",
      "What do you want me to know about finding hope and meaning through spiritual belief?",
      "If I'm facing the end of my own life, what spiritual preparation and peace would you want for me?"
    ]
  }
]

// Utility function to count questions in this file
export function getMassiveLegacyQuestionCount(): number {
  return massiveLegacyQuestions.reduce((total, template) => total + template.questions.length, 0)
}

// Function to get questions by specific tags
export function getQuestionsByTags(tags: string[]): string[] {
  return massiveLegacyQuestions
    .filter(template => tags.some(tag => template.tags.includes(tag)))
    .flatMap(template => template.questions)
}

// Function to get all questions as flat array for database seeding
export function getAllMassiveQuestions(): string[] {
  return massiveLegacyQuestions.flatMap(template => template.questions)
}